### ISSUE TITLE
NUM should include fractions and possibly time

### ISSUE THREAD

**Issue by danielhers** [nschneid/amr-hackathon#10]
Currently the `NUM` regex matches decimal numbers, but e.g. `1/7` is parsed as `STR`. Same for decimals without a leading digit: `.270`.
These should be considered numbers too.
Possibly, also times like `15:00` should be `NUM`, and maybe also ordinals like `3rd` and `#8722`.

**Comment by nschneid** [comment]
`NUM` is a syntactic category, not a semantic one—i.e., anything in quotes in the AMR is considered a string insofar as AMR syntax is concerned. Do any of the above expressions ever occur without quotes?

**Comment by danielhers** [comment]
Good point. No, I think they always have quotes. I guess it's an artefact
of the annotation system...
